# Generated by Django 2.2.3 on 2020-06-25 09:00

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadvantage',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='优势详情'),
        ),
        migrations.AddField(
            model_name='companyadvantage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='adv_img/%Y/%m/%d/', verbose_name='优势图片'),
        ),
        migrations.AddField(
            model_name='companyadvantage',
            name='is_del',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='onlinemsg',
            name='weichat',
            field=models.CharField(default='guo20123762', max_length=70, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='research',
            name='author',
            field=models.CharField(default='知鱼定制', max_length=70, verbose_name='作者'),
        ),
    ]
