# Generated by Django 2.2.7 on 2020-12-05 13:06

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0002_auto_20200625_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=70, verbose_name='价值观标题')),
                ('excerpt', models.TextField(blank=True, default='', max_length=200, verbose_name='价值观内容')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '价值观表',
                'verbose_name_plural': '价值观表',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=70, verbose_name='名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cos_logo/%Y/%m/%d/', verbose_name='Logo')),
                ('excerpt', models.TextField(blank=True, default='', max_length=200, verbose_name='摘要')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, verbose_name='详情')),
                ('type', models.CharField(choices=[('Company', 'Company'), ('Media', 'Media')], default='Company', max_length=16, verbose_name='合作客户类型')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '合作伙伴表',
                'verbose_name_plural': '合作伙伴表',
            },
        ),
        migrations.CreateModel(
            name='SolutionAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=70, verbose_name='方案优势名称')),
                ('excerpt', models.TextField(blank=True, default='', max_length=200, verbose_name='方案风控摘要')),
                ('img', models.ImageField(blank=True, null=True, upload_to='solution_img/%Y/%m/%d/', verbose_name='方案风控图片')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, verbose_name='解决方案优势详情')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '方案优势表',
                'verbose_name_plural': '方案优势表',
            },
        ),
        migrations.CreateModel(
            name='SolutionWindControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=70, verbose_name='方案风控标题')),
                ('excerpt', models.TextField(blank=True, default='', max_length=200, verbose_name='方案风控摘要')),
                ('img', models.ImageField(blank=True, null=True, upload_to='solution_img/%Y/%m/%d/', verbose_name='方案风控图片')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, verbose_name='解决方案优势详情')),
                ('is_del', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=16, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '解决方案风控表',
                'verbose_name_plural': '解决方案风控表',
            },
        ),
        migrations.RemoveField(
            model_name='case',
            name='nav_cat',
        ),
        migrations.DeleteModel(
            name='Partnet',
        ),
        migrations.AddField(
            model_name='solution',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='gingernet.Product', verbose_name='产品组合'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_adv',
            field=models.ManyToManyField(blank=True, null=True, to='gingernet.SolutionAdvantage', verbose_name='解决方案优势'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_wc',
            field=models.ManyToManyField(blank=True, null=True, to='gingernet.SolutionWindControl', verbose_name='解决方案风控'),
        ),
    ]
