# Generated by Django 2.2.7 on 2020-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0003_auto_20201205_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutionadvantage',
            options={'verbose_name': '解决方案优势表', 'verbose_name_plural': '解决方案优势表'},
        ),
        migrations.AlterField(
            model_name='solutionadvantage',
            name='excerpt',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='解决方案风控摘要'),
        ),
        migrations.AlterField(
            model_name='solutionadvantage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='solution_img/%Y/%m/%d/', verbose_name='解决方案风控图片'),
        ),
        migrations.AlterField(
            model_name='solutionadvantage',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='解决方案优势名称'),
        ),
        migrations.AlterField(
            model_name='solutionwindcontrol',
            name='excerpt',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='解决方案风控摘要'),
        ),
        migrations.AlterField(
            model_name='solutionwindcontrol',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='solution_img/%Y/%m/%d/', verbose_name='解决方案风控图片'),
        ),
        migrations.AlterField(
            model_name='solutionwindcontrol',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='解决方案风控标题'),
        ),
    ]
