# Generated by Django 2.2.7 on 2021-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0004_auto_20201206_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfunc',
            name='position',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='NO', max_length=16, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='productfunc',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='productfunc',
            name='is_del',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Left', max_length=16, verbose_name='是否删除'),
        ),
    ]
