# Generated by Django 2.2.7 on 2021-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0005_auto_20210107_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvantage',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='序号'),
        ),
    ]
