# Generated by Django 2.2.7 on 2021-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0006_productadvantage_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionadvantage',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='序号'),
        ),
    ]
