# Generated by Django 2.2.7 on 2021-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingernet', '0009_solutionwindcontrol_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvantage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/', verbose_name='优势Icon'),
        ),
        migrations.AddField(
            model_name='productfunc',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/', verbose_name='产品Icon'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Media', 'Media'), ('Costomer', 'Costomer')], default='Company', max_length=16, verbose_name='合作客户类型'),
        ),
    ]
